import type { Prisma } from "@prisma/client";

export const collegeDomainSeeds = [
  {
    domain: "iitb.ac.in",
    collegeName: "IIT Bombay",
    type: "IIT",
    tier: "ELITE",
    state: "Maharashtra",
    city: "Mumbai",
    website: "https://www.iitb.ac.in",
    isApproved: true,
  },
  {
    domain: "iitd.ac.in",
    collegeName: "IIT Delhi",
    type: "IIT",
    tier: "ELITE",
    state: "Delhi",
    city: "New Delhi",
    website: "https://home.iitd.ac.in",
    isApproved: true,
  },
  {
    domain: "iitm.ac.in",
    collegeName: "IIT Madras",
    type: "IIT",
    tier: "ELITE",
    state: "Tamil Nadu",
    city: "Chennai",
    website: "https://www.iitm.ac.in",
    isApproved: true,
  },
  {
    domain: "iitk.ac.in",
    collegeName: "IIT Kanpur",
    type: "IIT",
    tier: "ELITE",
    state: "Uttar Pradesh",
    city: "Kanpur",
    website: "https://www.iitk.ac.in",
    isApproved: true,
  },
  {
    domain: "iitkgp.ac.in",
    collegeName: "IIT Kharagpur",
    type: "IIT",
    tier: "ELITE",
    state: "West Bengal",
    city: "Kharagpur",
    website: "https://www.iitkgp.ac.in",
    isApproved: true,
  },
  {
    domain: "iith.ac.in",
    collegeName: "IIT Hyderabad",
    type: "IIT",
    tier: "ELITE",
    state: "Telangana",
    city: "Hyderabad",
    website: "https://www.iith.ac.in",
    isApproved: true,
  },
  {
    domain: "iitg.ac.in",
    collegeName: "IIT Guwahati",
    type: "IIT",
    tier: "ELITE",
    state: "Assam",
    city: "Guwahati",
    website: "https://iitg.ac.in",
    isApproved: true,
  },
  {
    domain: "iitr.ac.in",
    collegeName: "IIT Roorkee",
    type: "IIT",
    tier: "ELITE",
    state: "Uttarakhand",
    city: "Roorkee",
    website: "https://www.iitr.ac.in",
    isApproved: true,
  },
  {
    domain: "nitt.edu",
    collegeName: "NIT Trichy",
    type: "NIT",
    tier: "VERIFIED",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    website: "https://nitt.edu",
    isApproved: true,
  },
  {
    domain: "nitw.ac.in",
    collegeName: "NIT Warangal",
    type: "NIT",
    tier: "VERIFIED",
    state: "Telangana",
    city: "Warangal",
    website: "https://nitw.ac.in",
    isApproved: true,
  },
  {
    domain: "nitk.edu.in",
    collegeName: "NIT Karnataka",
    type: "NIT",
    tier: "VERIFIED",
    state: "Karnataka",
    city: "Surathkal",
    website: "https://www.nitk.edu.in",
    isApproved: true,
  },
  {
    domain: "nitc.ac.in",
    collegeName: "NIT Calicut",
    type: "NIT",
    tier: "VERIFIED",
    state: "Kerala",
    city: "Kozhikode",
    website: "https://nitc.ac.in",
    isApproved: true,
  },
  {
    domain: "pilani.bits-pilani.ac.in",
    collegeName: "BITS Pilani",
    type: "BITS",
    tier: "ELITE",
    state: "Rajasthan",
    city: "Pilani",
    website: "https://www.bits-pilani.ac.in/pilani",
    isApproved: true,
  },
  {
    domain: "goa.bits-pilani.ac.in",
    collegeName: "BITS Goa",
    type: "BITS",
    tier: "ELITE",
    state: "Goa",
    city: "Zuarinagar",
    website: "https://www.bits-pilani.ac.in/goa",
    isApproved: true,
  },
  {
    domain: "hyderabad.bits-pilani.ac.in",
    collegeName: "BITS Hyderabad",
    type: "BITS",
    tier: "ELITE",
    state: "Telangana",
    city: "Hyderabad",
    website: "https://www.bits-pilani.ac.in/hyderabad",
    isApproved: true,
  },
  {
    domain: "bmsit.in",
    collegeName: "BMS Institute of Technology & Management",
    type: "PRIVATE",
    tier: "VERIFIED",
    city: "Bengaluru",
    state: "Karnataka",
    website: "https://bmsit.ac.in",
    isApproved: true,
  },
] satisfies Prisma.CollegeDomainCreateInput[];
